window.ANCIENTFRAME = window.ANCIENTFRAME || {};
ANCIENTFRAME.calculators = [
 {title:"Rafter Calculator",slug:"rafter",description:"Rafter length, rise, run and roof angle from familiar measurements.",url:"calculators/rafter.html"},
 {title:"Stair Calculator",slug:"stairs",description:"Riser height, tread depth, total run and stringer geometry.",url:"calculators/stairs.html"},
 {title:"Roof Framing",slug:"roof-framing",description:"Roof pitch, half-span run and common rafter geometry.",url:"calculators/roof-framing.html"},
 {title:"Arched Opening",slug:"arched-opening",description:"Circular arch radius and arc geometry for curved openings.",url:"calculators/arched-opening.html"},
 {title:"Oval Opening",slug:"oval-opening",description:"Ellipse dimensions, area and perimeter approximation.",url:"calculators/oval-opening.html"},
 {title:"Angles & Geometry",slug:"angles",description:"Right-triangle sides, hypotenuse and angles.",url:"calculators/angles.html"}
];
ANCIENTFRAME.guides = [
 {title:"How to Think About Rafter Length",slug:"rafter-length",excerpt:"Understand the relationship between run, rise and the diagonal length of a common rafter.",date:"2026-09-23",category:"Roof framing",body:"<p>A common rafter is the hypotenuse of the right triangle formed by the horizontal run and vertical rise. Once those two dimensions are known, the diagonal length follows from the Pythagorean theorem.</p><h2>Run and rise come first</h2><p>For a simple roof triangle, the run is the horizontal distance from the outside wall to the ridge reference point. The rise is the vertical distance from the top of the wall reference to the ridge. Keep the measurement references consistent before calculating.</p><h2>Use the result carefully</h2><p>AncientFrame displays results in practical feet-and-inch fractions. The displayed dimension is rounded for field readability, so verify the unrounded geometry and account for actual material thickness, ridge details, seat cuts, overhangs and the construction method being used.</p>},
 {title:"Understanding Roof Pitch",slug:"roof-pitch",excerpt:"A practical explanation of rise over run and how pitch becomes an angle.",date:"2026-09-23",category:"Roof framing",body:"<p>Roof pitch is commonly expressed as rise over a twelve-inch horizontal run. An 8/12 roof rises eight inches for every twelve inches of run.</p><h2>Pitch and angle are related</h2><p>The pitch ratio can be converted to an angle using the arctangent of rise divided by run. The ratio is often easier to communicate in framing work, while the angle is useful for geometry and layout.</p>},
 {title:"Stair Rise and Run",slug:"stair-rise-and-run",excerpt:"How total rise, risers and tread depth work together in a stair layout.",date:"2026-09-23",category:"Stairs",body:"<p>Stair layout begins with total vertical rise. Dividing that rise by the number of risers gives the individual riser height. Tread depth then determines the horizontal run and the resulting stringer geometry.</p><h2>Verify local requirements</h2><p>Stair dimensions are subject to building-code requirements that vary by jurisdiction and building type. Use a calculator to explore the geometry, then verify the final layout against the applicable requirements.</p>}
];
